version: '1.0.{build}'
environment:
  nodejs_version: "8"
platform: Any CPU
notifications:
- provider: Slack
  auth_token:
    secure: Q+xg4/yU5OR9BVF14cw4yZ+3qlhMeYDsAhUQyOIszmF1mHvq44tIvQpWByBJCd/cgUIZk3SwBpk4hh1MrkQIk6rnaOZ2LNBTev4zrq36oXk=
  channel: '#builds'
install:
- ps: Install-Product node $env:nodejs_version
- npm install
test_script:
- npm run lint
- npm run build
- npm run test:coveralls
build: off